### PR TITLE
Lifecycle

### LINKED ISSUE #158: Edit item with "généalogie de bout-en-bout" to "Cycle de vie"

### PR DESCRIPTION
**Pull request by ClementMayer**
Close #158 : Edit item with "généalogie de bout-en-bout" to "Cycle de vie"

### CODE REVIEW

**Review by meuce — COMMENTED** [review]
OK with the "lifecycle" / "cycle de vie" notion. I would like to make the proposition to remove the "end-to-end" part sometimes associated with it, this notion being for me included in the lifecycle idea. For example, line 237 in referentiel_evaluation.md "cycle de vie de bout-en-bout", seems to me as a bit redundant. Nevertheless, I would be ok with the association of this notion with the documenting aspect, like "documentation de bout-en-bout du cycle de vie du modèle".

**Comment by SaboniAmine** [comment]
I would agree with @meuce, "end-to-end" might be a confusing notion when we talk about products including ML. To illustrate this non linearity, the [_Hidden Technical Debt in Machine Learning Systems_ ](https://proceedings.neurips.cc/paper/2015/file/86df7dcfd896fcaf2674f757a2463eba-Paper.pdf) paper might be interesting here.

**Review by HeytemBou — APPROVED** [review]
I agree with @SaboniAmine , the term "life-cycle" captures the non-linearity nature of ML projects more than somewhat linear vibe given by the term "end-to-end"

**Comment by bowni** [comment]
OK thank you folks, will adjust accordingly!

**Review by SaboniAmine — APPROVED** [review]

**Review by meuce — APPROVED** [review]

**Pull request merged**
